/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppRelatoriosRouteImport } from './routes/_app.relatorios'
import { Route as AppPlanejamentoRouteImport } from './routes/_app.planejamento'
import { Route as AppPerformanceRouteImport } from './routes/_app.performance'
import { Route as AppMercadoLivreRouteImport } from './routes/_app.mercado-livre'
import { Route as AppMagazineLuizaRouteImport } from './routes/_app.magazine-luiza'
import { Route as AppEstoqueRouteImport } from './routes/_app.estoque'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCentralDadosRouteImport } from './routes/_app.central-dados'
import { Route as AppCentralAlertasRouteImport } from './routes/_app.central-alertas'
import { Route as AppCampanhasRouteImport } from './routes/_app.campanhas'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanejamentoRoute = AppPlanejamentoRouteImport.update({
  id: '/planejamento',
  path: '/planejamento',
  getParentRoute: () => AppRoute,
} as any)
const AppPerformanceRoute = AppPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppMercadoLivreRoute = AppMercadoLivreRouteImport.update({
  id: '/mercado-livre',
  path: '/mercado-livre',
  getParentRoute: () => AppRoute,
} as any)
const AppMagazineLuizaRoute = AppMagazineLuizaRouteImport.update({
  id: '/magazine-luiza',
  path: '/magazine-luiza',
  getParentRoute: () => AppRoute,
} as any)
const AppEstoqueRoute = AppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCentralDadosRoute = AppCentralDadosRouteImport.update({
  id: '/central-dados',
  path: '/central-dados',
  getParentRoute: () => AppRoute,
} as any)
const AppCentralAlertasRoute = AppCentralAlertasRouteImport.update({
  id: '/central-alertas',
  path: '/central-alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/campanhas': typeof AppCampanhasRoute
  '/central-alertas': typeof AppCentralAlertasRoute
  '/central-dados': typeof AppCentralDadosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/estoque': typeof AppEstoqueRoute
  '/magazine-luiza': typeof AppMagazineLuizaRoute
  '/mercado-livre': typeof AppMercadoLivreRoute
  '/performance': typeof AppPerformanceRoute
  '/planejamento': typeof AppPlanejamentoRoute
  '/relatorios': typeof AppRelatoriosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/campanhas': typeof AppCampanhasRoute
  '/central-alertas': typeof AppCentralAlertasRoute
  '/central-dados': typeof AppCentralDadosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/estoque': typeof AppEstoqueRoute
  '/magazine-luiza': typeof AppMagazineLuizaRoute
  '/mercado-livre': typeof AppMercadoLivreRoute
  '/performance': typeof AppPerformanceRoute
  '/planejamento': typeof AppPlanejamentoRoute
  '/relatorios': typeof AppRelatoriosRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/campanhas': typeof AppCampanhasRoute
  '/_app/central-alertas': typeof AppCentralAlertasRoute
  '/_app/central-dados': typeof AppCentralDadosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/estoque': typeof AppEstoqueRoute
  '/_app/magazine-luiza': typeof AppMagazineLuizaRoute
  '/_app/mercado-livre': typeof AppMercadoLivreRoute
  '/_app/performance': typeof AppPerformanceRoute
  '/_app/planejamento': typeof AppPlanejamentoRoute
  '/_app/relatorios': typeof AppRelatoriosRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campanhas'
    | '/central-alertas'
    | '/central-dados'
    | '/configuracoes'
    | '/estoque'
    | '/magazine-luiza'
    | '/mercado-livre'
    | '/performance'
    | '/planejamento'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/campanhas'
    | '/central-alertas'
    | '/central-dados'
    | '/configuracoes'
    | '/estoque'
    | '/magazine-luiza'
    | '/mercado-livre'
    | '/performance'
    | '/planejamento'
    | '/relatorios'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/campanhas'
    | '/_app/central-alertas'
    | '/_app/central-dados'
    | '/_app/configuracoes'
    | '/_app/estoque'
    | '/_app/magazine-luiza'
    | '/_app/mercado-livre'
    | '/_app/performance'
    | '/_app/planejamento'
    | '/_app/relatorios'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/relatorios': {
      id: '/_app/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planejamento': {
      id: '/_app/planejamento'
      path: '/planejamento'
      fullPath: '/planejamento'
      preLoaderRoute: typeof AppPlanejamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/performance': {
      id: '/_app/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AppPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mercado-livre': {
      id: '/_app/mercado-livre'
      path: '/mercado-livre'
      fullPath: '/mercado-livre'
      preLoaderRoute: typeof AppMercadoLivreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/magazine-luiza': {
      id: '/_app/magazine-luiza'
      path: '/magazine-luiza'
      fullPath: '/magazine-luiza'
      preLoaderRoute: typeof AppMagazineLuizaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estoque': {
      id: '/_app/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AppEstoqueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/central-dados': {
      id: '/_app/central-dados'
      path: '/central-dados'
      fullPath: '/central-dados'
      preLoaderRoute: typeof AppCentralDadosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/central-alertas': {
      id: '/_app/central-alertas'
      path: '/central-alertas'
      fullPath: '/central-alertas'
      preLoaderRoute: typeof AppCentralAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanhas': {
      id: '/_app/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppCentralAlertasRoute: typeof AppCentralAlertasRoute
  AppCentralDadosRoute: typeof AppCentralDadosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEstoqueRoute: typeof AppEstoqueRoute
  AppMagazineLuizaRoute: typeof AppMagazineLuizaRoute
  AppMercadoLivreRoute: typeof AppMercadoLivreRoute
  AppPerformanceRoute: typeof AppPerformanceRoute
  AppPlanejamentoRoute: typeof AppPlanejamentoRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampanhasRoute: AppCampanhasRoute,
  AppCentralAlertasRoute: AppCentralAlertasRoute,
  AppCentralDadosRoute: AppCentralDadosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEstoqueRoute: AppEstoqueRoute,
  AppMagazineLuizaRoute: AppMagazineLuizaRoute,
  AppMercadoLivreRoute: AppMercadoLivreRoute,
  AppPerformanceRoute: AppPerformanceRoute,
  AppPlanejamentoRoute: AppPlanejamentoRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
